### PR TITLE
Add driver/date-add function necessary to queries with relative date

### PR DESCRIPTION
**Pull request by rodrigodc07**

### CODE REVIEW

**Comment by dacort** [comment]
@rodrigodc07 Let me know if this is ready to go, and thanks for adding this! Was just reviewing date support the other day and seemed like it was lacking a bit.

**Comment by rodrigodc07** [comment]
Sorry for the delay, we were testing it, and it's ready to go

**Comment by kekcogen** [comment]
Thanks for contribution. We are waiting exactly for this feature =)

**Comment by dacort** [comment]
I should be able to review and merge this weekend, looks pretty straight-forward!

**Comment by dacort** [comment]
Looks good to me - I tested with v0.33.4 of Metabase. I had to update my local dependencies, but other than that no issues. Thanks again @rodrigodc07.

**Pull request merged**
